MySQL:
  # activate MySQL
  active: false
  # hostname to use to connect to the database, in most cases 'localhost'
  hostname: host
  # username to use to connect to the database
  username: user
  # password to use to connect to the database
  password: pw
  # database name to connect to
  database: db
  # database port to connect to
  port: 3306
  # general statistic table name
  table: mobstats
  # kill statistic table name
  killtable: mobkillstats
  # connection options
  options: ?autoReconnect=true
# === [ SQLite Settings ] ===
SQLite:
  # database file name, plugin will append extension '.db'
  filename: database
  # activate SQLite
  active: false
  # general statistic table name
  table: mobstats
  # kill statistic table name
  killtable: mobkillstats
# === [ YML Database Emulation Settings ] ===
YML:
  # general statistic file name, plugin will append extension '.yml'
  table: mobstats
  # # kill statistic file name, plugin will append extension '.yml'
  killtable: mobkillstats
  # really save every kill? This is not advised for YML!
  collectPreciseOverride: false
# === [ Statistic Settings ] ===
statistics:
  # clear (duplicated) statistics on every start
  clearOnStart: true
  # create empty player entry when they join
  createOnJoin: true
  # prevent stats for players without the permission 'mobstats.nonewbie'
  checkNewbies: true
  # order deaths descending by default (rather than TOP deaths being LESS deaths)
  deathsDescending: false
  # save every kill - is never read internally, so only for web stats or alike
  collectPrecise: true
  # count mobs killing other mobs
  countMobVsMob: true
  # player meta that marks players as not counting, for example 'NPC' for most plugins that add them
  preventingPlayerMeta:
  - NPC
  # always reset a streak when a player disconnects
  resetKillstreakOnQuit: false
  # seconds to wait before the top/flop leaderboard values will query the database again
  leaderboardRefresh: 60
  # announce lines from streak_announcements.yml on specific streak values
  streakAnnouncements: false
  # issue commands from streak_commands.yml on specific streak values
  streakCommands: false
  # count dying from other sources than players (and their tamed pets) towards death count and resetting of streaks
  countRegularDeaths: false
  # count dying from other player's tamed pets for death count and resetting of streaks
  countPetDeaths: false
  # mathematical formula to calculate kill/death ratio
  killDeathCalculation: '&k/(&d+1)'
  # simplify kill/death ratio calculation to just kills per deaths
  killDeathSimple: false
  # time in seconds to consider a former kill an assist
  assistSeconds: 60
# === [ Integration into other Plugins ] ===
other:
  # use players' display names
  displayNames: false
  # count PVP Arena deaths
  PVPArena: false
  OPMessages: true
# world names where not to count statistics
ignoreworlds:
  - doNotTrack
# locations of leaderboards
leaderboards: []
msg:
  overrides: false
  main:
    - '&cName: &7%n'
    - '&cKills: &7%k'
    - '&cDeaths: &7%d'
    - '&cRatio: &7%r'
    - '&cStreak: &7%s'
    - '&cMax Streak: &7%m'
# === [ Updater Settings ] ===
update:
  # what to do? Valid values: off, announce, download, both
  mode: both
  # which type of branch to get updates? Valid values: dev, alpha, beta, release
  type: beta
# === [ bStats Metrics Settings ] ===
bStats:
  # Should we send stats at all? Please keep this in so we have an overview of spread of versions <3
  enabled: true
  # This setting sends a bit more detailed information about which features are used at all. Thank you for supporting me!
  full: true