name: Java CI with Maven

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set plugin.yml version
      run: |
        sed -i 's/build-number/'$GITHUB_RUN_NUMBER'/g' src/main/resources/plugin.yml
    - name: Build with Maven
      run: mvn clean package --batch-mode
    - uses: actions/upload-artifact@v1
      with:
        name: plugin-files
        path: target/mobstats.jar